# Special Characters replaced by sdvx_helper.pyw as windows doesn't allow them as file names: '\\', '/', ':', '*', '?', '"', '<', '>', '|'
special_titles = {
        'Death by Glamour  華麗なる死闘':  'Death by Glamour / 華麗なる死闘',
        'Electric Sister Bitch':'Electric "Sister" Bitch',
        'Lunatic Dial':'Lunartic Dial',
        'ASGORE  アズゴア':'ASGORE / アズゴア',
        'archivezip':'archive::zip',
        'Sakura Reflection (PLight Slayer Remix)':'Sakura Reflection (P*Light Slayer Remix)',
        'Spider Dance  スパイダーダンス':'Spider Dance / スパイダーダンス',
        'U.N. Owen was her (Hyuji Remix)':'U.N. Owen was her? (Hyuji Remix)',
        'I’m Your Treasure Box ＊あなたは マリンせんちょうを たからばこからみつけた。':'I’m Your Treasure Box ＊あなたは マリンせんちょうを たからばこからみつけた。',
        'The Sampling Paradise (PLight Remix)':'The Sampling Paradise (P*Light Remix)',
        'Finale  フィナーレ':'Finale / フィナーレ',
        'コンベア速度Max!しゃいにん☆廻転ズシSushi&Peace':'コンベア速度Max!? しゃいにん☆廻転ズシ"Sushi&Peace"',
        'コンベア速度Max! しゃいにん☆廻転ズシSushi&Peace':'コンベア速度Max!? しゃいにん☆廻転ズシ"Sushi&Peace"',
        'VoynichManuscript':'Voynich:Manuscript',        
        'Believe (y)our Wings {VIVID RAYS}':'Believe (y)our Wings {V:IVID RAYS}',
        'チルノのパーフェクトさんすう教室　⑨周年バージョン':'チルノのパーフェクトさんすう教室　⑨周年バージョン',
        'Wuv U(picoustic rmx)':'Wuv U(pico/ustic rmx)',
        'Battle Against a True Hero  本物のヒーローとの戦い':'Battle Against a True Hero / 本物のヒーローとの戦い',
        'rEVoltagers':'rE:Voltagers',
        'S1CK F41RY':'S1CK_F41RY',
        'ニ分間の世界':'二分間の世界',
        'ReRose Gun Shoooot!':'Re:Rose Gun Shoooot!',
        'gigadelic (かめりあ\'s The TERA RMX)':'gigadelic (かめりあ\'s "The TERA" RMX)',
        'PROVOESPROPOSE êl fine':'PROVOES*PROPOSE <<êl fine>>',
        'LuckyClover':'Lucky*Clover',
        '壊Raveit!! 壊Raveit!!':'壊Rave*it!! 壊Rave*it!!',
        'BLACK or WHITE':'BLACK or WHITE?',
        'MrVIRTUALIZER':'Mr.VIRTUALIZER',
        '#Fairy dancing in lake':'#Fairy_dancing_in_lake',
        '゜。Chantilly Fille。°':'゜*。Chantilly Fille。*°',
        '侵蝕コード 666 -今日ちょっと指 (略-':'侵蝕コード：666　-今日ちょっと指（略-',
        '侵蝕コード：666　-今日ちょっと指（略-':'侵蝕コード：666　-今日ちょっと指（略-',
        '隅田川夏恋歌IO Angel mix':'隅田川夏恋歌 (I/O Angel mix)',
        '隅田川純恋歌IO Angel mix':'隅田川夏恋歌 (I/O Angel mix)',
        '隅田川純恋歌I/O Angel mix':'隅田川夏恋歌 (I/O Angel mix)',
        '隅田川夏恋歌 (IO Angel mix)':'隅田川夏恋歌 (I/O Angel mix)',
        'ハナビラリンクス':'ハナビラ:リンクス',
        'Heartache  心の痛み':'Heartache / 心の痛み',
        'Chantilly Fille':'゜*。Chantilly Fille。*°',
        'infinite youniverse':'infinite:youniverse',
        'infiniteyouniverse':'infinite:youniverse',
        '#FairyJoke #SDVX Edit':'#FairyJoke #SDVX_Edit',
        'Spear of Justice  正義の槍':'Spear of Justice / 正義の槍',
        'ReEnd of a Dream':'Re：End of a Dream',
        'Divine\'sBugscript':'Divine\'s:Bugscript',
        'ReElemental Creation':'Re：Elemental Creation',
        'Recall':'Re:call',
        'Sacrifice Escape 不条理の模倣による感情と代償':'Sacrifice Escape: 不条理の模倣による感情と代償',
        'Lachryma《ReQueen’M》':'Lachryma《Re:Queen’M》',
        '《Reminiscence》':'《Re:miniscence》',
        'DIABLOSISNāga':'DIABLOSIS::Nāga',
        'FLügeL《ΛrpΣggyØ》':'FLügeL《Λrp:ΣggyØ》',
        '†OLPHEUX†':'†:OLPHEUX:†',
        'FIRSTDREAMS':'FIRST：DREAMS',
        'Fl0ating':'Fl0ating:',
        'HP1':'HP:1',
        'OpsCode-Rapture-':'Ops:Code-Rapture-',
        'ReRHYZE':'Re:RHYZE',
        'TOYBOX CANNØN=͟͟͞ Σ≡=｡ﾟ.+｡.☆':'TOYBOX CANNØN=͟͟͞ Σ≡=｡ﾟ:*.:+｡.☆',
        'ToBrandNewDeadline':'To:BrandNewDeadline',
        'apollioth':'apo:llioth',
        'partystage':'party:stage',
        'rEVoltagers':'rE:Voltagers',
        'ΛNXIENTLEGΛXIEZ':'ΛNXIENT:LEGΛXIEZ',
        'Φnd:you':'Φnd:you',
        'Яeson D\'être':'Яe:son D\'être',
        'MeTear':'Me:Tear',
        'clearwings':'clear:wings',
        '過食性アイドル症候群':'過食性:アイドル症候群',
        'ハナビラリンクス':'ハナビラ:リンクス',
        '君色サブリミナル(Arranged Iceon)':'君色サブリミナル(Arranged: Iceon)',
        '取り残された美術(ArrangedHiZuMi)':'取り残された美術(Arranged:HiZuMi)',
        'スラッシュシスターズ':'スラッシュ//シスターズ',
        ' Erm, could it be a Spatiotemporal ShockWAVE Syndrome...':'* Erm, could it be a Spatiotemporal ShockWAVE Syndrome...?',
        'Feels Seasickness...':'*Feels Seasickness...*',
        'For.tune':'For.*tune',
        'U.N.オーエンは彼女なのかharu naba Remix':'U.N.オーエンは彼女なのか？haru_naba Remix',
        'U.N.オーエンは彼女なのか？haru naba Remix':'U.N.オーエンは彼女なのか？haru_naba Remix',
        'With It This Heaven':'With It This Heaven?',
        'メイビ～初恋！ビスケット☆大作戦':'メイビ～初恋！？ビスケット☆大作戦',
        '恋愛♡悪戯！まじかる☆ぱふゅ～む！！':'恋愛♡悪戯！？まじかる☆ぱふゅ～む！！',
        'Black or Red':'Black or Red?',
        'U.N.オーエンは彼女なのか(TO-HOlic mix)':'U.N.オーエンは彼女なのか？(TO-HOlic mix)',
        '偶然 必然 アンビバレンス！':'偶然？ 必然？ アンビバレンス！',
        '恋はどうモロ◎波動OK☆方程式!!':'恋はどう？モロ◎波動OK☆方程式!!',
        '青春☆してるかいREADY&LADY!':'青春☆してるかい？READY&LADY!',
        'えあぁ、そう。':'え？あぁ、そう。',
        'Cuz we 3 this Game':'Cuz we <3 this Game',
        'ΛNXIENTLEGΛXIEZ':'ΛNXIENT:LEGΛXIEZ',
        'BLAZING LAZER':'BLAZING_LAZER',
        'GIGI BABA(brz style)':'GIGI BABA(brz_style)',
        'Lovesick Lovetune(brz style)' :'Lovesick Lovetune(brz_style)',
        'WONDER WOBBLER':'WONDER WOBBLER',
        'WobbleTangleFestival (影虎。 & ikaruga nex\'s HDM RMX)':'WobbleTangleFestival (影虎。 & ikaruga_nex\'s HDM RMX)',
        'WONDER WOBBLER':'WONDER_WOBBLER',
        'Erm, could it be a Spatiotemporal ShockWAVE Syndrome...':'* Erm, could it be a Spatiotemporal ShockWAVE Syndrome...?',
        'cloche(といぼっくすうぃんぐ みっくす)':'cloche(といぼっくすうぃんぐ　みっくす)',
        'Critical Crystal(brz remix)':'Critical Crystal(brz_remix)',
}

direct_overides = {
    'Pure Evil': {'NOV:5','ADV:12','EXH:17'},
    'チルノのパーフェクトさんすう教室　⑨周年バージョン':{'NOV:5','ADV:11','EXH:13','APPEND:16'},
    'チルノのパーフェクトさんすう教室 ⑨周年バージョン':{'NOV:5','ADV:11','EXH:13','APPEND:16'},
    'グレイスちゃんの超～絶!!グラビティ講座w':{'APPEND:1'},
    'マキシマ先生の満開!!ヘヴンリー講座♥':{'APPEND:1'},
    'エクシード仮面ちゃんのちょっと一線をえくしーどしたEXCEED講座':{'APPEND:1'}
}

ignored_names = {
    'Help me, CODYYYYYY!!'
}

direct_removes = {
    '侵蝕コード：666　-今日ちょっと指（略-',    
}