package com.sdvxhelper.app.repository;

import java.io.File;
import java.net.URL;
import java.util.List;
import java.util.Map;

import com.sdvxhelper.repository.SettingsRepository;
import com.sdvxhelper.util.StringUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Verifies that {@link SettingsRepository} can load settings files that were
 * written by the Python version of SDVX Helper ({@code settings-bad.json}) as
 * well as files generated by the Java version ({@code settings-ok.json}).
 *
 * <p>
 * The Python format uses native JSON types (numbers, booleans, arrays, nested
 * objects) instead of the all-string representation the Java version writes.
 * {@code SettingsRepository} must convert every value to a {@code String} so
 * callers receive a uniform {@code Map<String, String>} regardless of the
 * file's origin.
 * </p>
 */
class SettingsRepositoryMigrationTest {

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private File fixture(String name) {
        URL url = getClass().getClassLoader().getResource(name);
        Assertions.assertNotNull(url, "Test fixture not found on classpath: " + name);
        return new File(url.getFile());
    }

    // =========================================================================
    // settings-bad.json (Python / native-JSON-type format)
    // =========================================================================

    @Test
    void badJsonLoadsWithoutException() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();
        Assertions.assertNotNull(settings);
        Assertions.assertFalse(settings.isEmpty());
    }

    @Test
    void badJsonIntegerValuesConvertedToString() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        // "lx": 2983 (bare JSON integer)
        Assertions.assertEquals("2983", settings.get("lx"));
        // "ly": 32
        Assertions.assertEquals("32", settings.get("ly"));
        // "autosave_interval": 60
        Assertions.assertEquals("60", settings.get("autosave_interval"));
        // "play0_interval": 10
        Assertions.assertEquals("10", settings.get("play0_interval"));
        // "logpic_offset_time": 2
        Assertions.assertEquals("2", settings.get("logpic_offset_time"));
        // "logpic_bg_alpha": 0
        Assertions.assertEquals("0", settings.get("logpic_bg_alpha"));
    }

    @Test
    void badJsonBooleanValuesConvertedToString() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        // "autosave_always": true
        Assertions.assertEquals("true", settings.get("autosave_always"));
        // "import_from_select": false
        Assertions.assertEquals("false", settings.get("import_from_select"));
        // "import_arcade_score": false
        Assertions.assertEquals("false", settings.get("import_arcade_score"));
        // "send_webhook": true
        Assertions.assertEquals("true", settings.get("send_webhook"));
        // "discord_presence_enable": true
        Assertions.assertEquals("true", settings.get("discord_presence_enable"));
    }

    @Test
    void badJsonDecimalValuesConvertedToString() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        // "detect_wait": 2.2 (bare JSON float)
        Assertions.assertEquals("2.2", settings.get("detect_wait"));
    }

    @Test
    void badJsonStringValuesArePreserved() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        Assertions.assertEquals("localhost", settings.get("host"));
        Assertions.assertEquals("4455", settings.get("port"));
        Assertions.assertEquals("SDVX Game Window - Main", settings.get("obs_source"));
        Assertions.assertEquals("Throdax", settings.get("player_name"));
        Assertions.assertEquals("en", settings.get("ui_language"));
        Assertions.assertEquals("resources/params.json", settings.get("params_json"));
    }

    @Test
    void badJsonEmptyArrayConvertedToEmptyListString() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        // "obs_enable_boot": [] → "[]"
        String raw = settings.get("obs_enable_boot");
        Assertions.assertNotNull(raw);
        List<String> list = StringUtils.parseListSetting(raw);
        Assertions.assertTrue(list.isEmpty(), "Empty JSON array should parse to empty list");
    }

    @Test
    void badJsonStringArrayConvertedToParseableString() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        // "obs_enable_select0": ["Volforce", "Song List Full", "Class", "MilkDrop"]
        String raw = settings.get("obs_enable_select0");
        Assertions.assertNotNull(raw);
        List<String> list = StringUtils.parseListSetting(raw);
        Assertions.assertEquals(4, list.size());
        Assertions.assertTrue(list.contains("Volforce"));
        Assertions.assertTrue(list.contains("Song List Full"));
        Assertions.assertTrue(list.contains("Class"));
        Assertions.assertTrue(list.contains("MilkDrop"));
    }

    @Test
    void badJsonMissingKeysAreMergedFromDefaults() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        // "orientation" key is absent from the Python file → default must be present
        Assertions.assertTrue(settings.containsKey("orientation"), "Key 'orientation' missing from defaults merge");
        // "score_lx" does not exist in the Python file → merged from defaults
        Assertions.assertTrue(settings.containsKey("score_lx"), "Key 'score_lx' missing from defaults merge");
    }

    @Test
    void badJsonAllValuesAreStrings() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-bad.json"));
        Map<String, String> settings = repo.load();

        for (Map.Entry<String, String> entry : settings.entrySet()) {
            Assertions.assertInstanceOf(String.class, entry.getValue(),
                    "Value for key '" + entry.getKey() + "' is not a String");
        }
    }

    // =========================================================================
    // settings-ok.json (Java / all-string format)
    // =========================================================================

    @Test
    void okJsonLoadsWithoutException() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-ok.json"));
        Map<String, String> settings = repo.load();
        Assertions.assertNotNull(settings);
        Assertions.assertFalse(settings.isEmpty());
    }

    @Test
    void okJsonStringValuesArePreserved() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-ok.json"));
        Map<String, String> settings = repo.load();

        Assertions.assertEquals("482", settings.get("lx"));
        Assertions.assertEquals("120", settings.get("ly"));
        Assertions.assertEquals("localhost", settings.get("host"));
        Assertions.assertEquals("4444", settings.get("port"));
        Assertions.assertEquals("false", settings.get("autosave_always"));
        Assertions.assertEquals("2.7", settings.get("detect_wait"));
    }

    @Test
    void okJsonEmptyListStringsRemainParseable() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-ok.json"));
        Map<String, String> settings = repo.load();

        // Values like "obs_enable_boot": "[]"
        List<String> list = StringUtils.parseListSetting(settings.get("obs_enable_boot"));
        Assertions.assertTrue(list.isEmpty());
    }

    @Test
    void okJsonMissingKeysAreMergedFromDefaults() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-ok.json"));
        Map<String, String> settings = repo.load();

        // settings-ok.json does not have every default key; missing ones must be merged
        Assertions.assertTrue(settings.containsKey("host"));
        Assertions.assertTrue(settings.containsKey("auto_update"));
    }

    @Test
    void okJsonAllValuesAreStrings() {
        SettingsRepository repo = new SettingsRepository(fixture("settings-ok.json"));
        Map<String, String> settings = repo.load();

        for (Map.Entry<String, String> entry : settings.entrySet()) {
            Assertions.assertInstanceOf(String.class, entry.getValue(),
                    "Value for key '" + entry.getKey() + "' is not a String");
        }
    }
}
